export const FIND_ALL_ORDER_FALSE = 'FIND_ALL_ORDER_FALSE';
export const FIND_ALL_ORDER_FALSE_AND_PROVIDERID = 'FIND_ALL_ORDER_FALSE_AND_PROVIDERID';
export const FIND_ALL_ORDER_MY_STORE = 'FIND_ALL_ORDER_MY_STORE';

export const ADD_ADDRESS = 'ADD_ADDRESS';
export const UPDATE_ADDRESS ='UPDATE_ADDRESS';
export const UPDATE_ADDRESS_DEFAULT = 'UPDATE_ADDRESS_DEFAULT';
export const DELETE_ADDRESS = 'DELETE_ADDRESS';
export const GET_ADDRESS_DETAIL= 'GET_ADDRESS_DETAIL';
export const VISIBLE_SELECT_TAG ='VISIBLE_SELECT_TAG';
export const INVISIBLE_SELECT_TAG = 'INVISIBLE_SELECT_TAG';
export const IS_CHECKOUT = 'IS_CHECKOUT';
export const ISNT_CHECKOUT='ISNT_CHECKOUT';
export const SELECT_ALL_TOGGLE = 'SELECT_ALL_TOGGLE';
export const ADD_LIST_PICTURE_RETURN_GOOD='ADD_LIST_PICTURE_RETURN_GOOD';