export const DELETE_AUTHORITIES= 'DELETE_AUTHORITIES';
export const ADD_AUTHORITIES = 'ADD_AUTHORITIES';
export const GET_ALL_ROLES = 'GET_ALL_ROLES';
export const GET_ALL_AUTHORITIES = 'GET_ALL_AUTHORITIES';
export const GET_ALL_USERS = 'GET_ALL_USERS';