//Thống kê
export const FIND_ALL_ACTION = 'FIND_ALL_ACTION';
export const FIND_ALL_STATISTICAL_ACTION ='FIND_ALL_STATISTICAL_ACTION';
export const CHART_PRODUCT_BY_MONTH_ACTION ='CHART_PRODUCT_BY_MONTH_ACTION';
export const CHART_PRODUCT_PARTNER_BY_MONTH_ACTION='CHART_PRODUCT_PARTNER_BY_MONTH_ACTION';
export const FIND_ALL_PRODUCT_BEST_VIEWS_ADMIN_ACTION ='FIND_ALL_PRODUCT_BEST_VIEWS_ADMIN_ACTION';
//Nhà cung cấp
export const ADD_PROVIDER_ACTION = 'ADD_PROVIDER_ACTION';
export const UPDATE_PROVIDER_ACTION = 'UPDATE_PROVIDER_ACTION';
export const DELETE_PROVIDER_ACTION = 'DELETE_PROVIDER_ACTION';
//Đối tác
export const UPDATE_PARTNER_ACTION = 'UPDATE_PARTNER_ACTION';
export const DELETE_PARTNER_ACTION = 'DELETE_PARTNER_ACTION';

//Cửa hàng
export const UPDATE_STATUS_SHOP_ACTION ='UPDATE_STATUS_SHOP_ACTION';
//Nhóm loại
export const ADD_CATEGORY_ACTION = 'ADD_CATEGORY_ACTION';
export const UPDATE_CATEGORY_ACTION = 'UPDATE_CATEGORY_ACTION';
export const DELETE_CATEGORY_ACTION = 'DELETE_CATEGORY_ACTION';
//Loại sản phẩm
export const ADD_SUB_CATEGORY_ACTION = 'ADD_SUB_CATEGORY_ACTION';
export const UPDATE_SUB_CATEGORY_ACTION = 'UPDATE_SUB_CATEGORY_ACTION';
export const DELETE_SUB_CATEGORY_ACTION = 'DELETE_SUB_CATEGORY_ACTION';
//Thương hiệu
export const ADD_BRAND_ACTION = 'ADD_BRAND_ACTION';
export const UPDATE_BRAND_ACTION = 'UPDATE_BRAND_ACTION';
export const DELETE_BRAND_ACTION = 'DELETE_BRAND_ACTION';
export const FIND_ALL_BRAND_BY_CATEGORY_ID_ACTION ='FIND_ALL_BRAND_BY_CATEGORY_ID_ACTION';

//Sản phẩm
export const GET_ALL_PRODUCT_SELLER_BY_PROVIDERNAME_ACTION = 'GET_ALL_PRODUCT_SELLER_BY_PROVIDERNAME_ACTION';
export const GET_ALL_REVIEW_OF_PRODUCT_BY_PROVIDERNAME_ACTION = 'GET_ALL_REVIEW_OF_PRODUCT_BY_PROVIDERNAME_ACTION';
export const ADD_PRODUCT_ACTION = 'ADD_PRODUCT_ACTION';
export const UPDATE_PRODUCT_ACTION = 'UPDATE_PRODUCT_ACTION';
export const UPDATE_PRODUCT_VIOLATION_ACTION = 'UPDATE_PRODUCT_VIOLATION_ACTION';
export const DELETE_PRODUCT_ACTION = 'DELETE_PRODUCT_ACTION';
export const ADD_PRODUCT_FORBIDDEN_ACTION = 'ADD_PRODUCT_FORBIDDEN_ACTION';
export const DELETE_PRODUCT_FORBIDDEN_ACTION ='DELETE_PRODUCT_FORBIDDEN_ACTION';
export const DELETE_PRODUCT_VIOLATION_ACTION = 'DELETE_PRODUCT_VIOLATION_ACTION';
export const FIND_ALL_PRODUCT_VIOLATION_ACTION = 'FIND_ALL_PRODUCT_VIOLATION_ACTION';
export const VIEW_FAST_USER_ACTION ='VIEW_FAST_USER_ACTION';
export const ADD_LIST_PRODUCT_ACTION = 'ADD_LIST_PRODUCT_ACTION';
export const UPDATE_STATUS_TRUE_LIST_PRODUCT_ACTION ='UPDATE_STATUS_TRUE_LIST_PRODUCT_ACTION';
//Người dùng
export const ADD_USER_ACTION = 'ADD_USER_ACTION';
export const UPDATE_USER_ACTION = 'UPDATE_USER_ACTION';
export const DELETE_USER_ACTION = 'DELETE_USER_ACTION';
export const ADD_USER_RESTRICTED_ACTION ='ADD_USER_RESTRICTED_ACTION';
export const UPDATE_USER_RESTRICTED_ACTION ='UPDATE_USER_RESTRICTED_ACTION';
export const DELETE_USER_RESTRICTED_ACTION = 'DELETE_USER_RESTRICTED_ACTION';
export const ADD_USER_RESTRICTED_ALL_ACTION ='ADD_USER_RESTRICTED_ALL_ACTION';

//Carousel
export const ADD_CAROUSEL_ACTION = 'ADD_CAROUSEL_ACTION';
export const UPDATE_CAROUSEL_ACTION = 'UPDATE_CAROUSEL_ACTION';
export const DELETE_CAROUSEL_ACTION ='DELETE_CAROUSEL_ACTION';
//Đơn vị tính
export const ADD_MEASURE_ACTION ='ADD_MEASURE_ACTION';
export const UPDATE_MEASURE_ACTION = 'UPDATE_MEASURE_ACTION';
export const DELETE_MEASURE_ACTION ='DELETE_MEASURE_ACTION';
//Sự kiện
export const ADD_EVENT_ACTION = 'ADD_EVENT_ACTION';
export const UPDATE_EVENT_ACTION = 'UPDATE_EVENT_ACTION';
export const DELETE_EVENT_ACTION = 'DELETE_EVENT_ACTION';
//Phần thưởng
export const ADD_REWARD_ACTION ='ADD_REWARD_ACTION';
export const UPDATE_REWARD_ACTION ='UPDATE_REWARD_ACTION';
export const DELETE_REWARD_ACTION ='DELETE_REWARD_ACTION';
export const ADD_REWARD_DETAIL_ACTION ='ADD_REWARD_DETAIL_ACTION';
export const UPDATE_REWARD_DETAIL_ACTION ='UPDATE_REWARD_DETAIL_ACTION';
export const DELETE_REWARD_DETAIL_ACTION ='DELETE_REWARD_DETAIL_ACTION';
export const FIND_ALL_REWARD_BY_EVENT_ID_ACTION ='FIND_ALL_REWARD_BY_EVENT_ID_ACTION';
//Mã giảm giá
export const ADD_VOUCHER_ADMIN_ACTION ='ADD_VOUCHER_ADMIN_ACTION';
export const UPDATE_VOUCHER_ADMIN_ACTION ='UPDATE_VOUCHER_ADMIN_ACTION';
export const DELETE_VOUCHER_ADMIN_ACTION ='DELETE_VOUCHER_ADMIN_ACTION';
export const ADD_FAST_VOUCHER_ADMIN_ACTION = 'ADD_FAST_VOUCHER_ADMIN_ACTION';
//Vai trò
export const ADD_ROLE_ADMIN_ACTION ='ADD_ROLE_ADMIN_ACTION';
export const UPDATE_ROLE_ADMIN_ACTION ='UPDATE_ROLE_ADMIN_ACTION';
export const DELETE_ROLE_ADMIN_ACTION ='DELETE_ROLE_ADMIN_ACTION';
