export const GET_ALL_PRODUCT_SELLER_ACTION ='GET_ALL_PRODUCT_SELLER_ACITON';
export const ADD_PRODUCT_SELLER_ACTION = 'ADD_PRODUCT_SELLER_ACTION';
export const UPDATE_PRODUCT_SELLER_ACTION ='UPDATE_PRODUCT_SELLER_ACTION';
export const DELETE_PRODUCT_SELLER_ACTION ='DELETE_PRODUCT_SELLER_ACTION';
export const FIND_ALL_STATISTICAL_SELLER_ACTION = 'FIND_ALL_STATISTICAL_SELLER_ACTION';
export const FIND_ALL_PRODUCT_BEST_VIEWS_SELLER_ACTION ='FIND_ALL_PRODUCT_BEST_VIEWS_SELLER_ACTION';
export const GET_REFERENCES_PRODUCT_ACTION = 'GET_REFERENCES_PRODUCT_ACTION';
export const GET_MY_STORE_ACTION = 'GET_MY_STORE_ACTION';
export const UPDATE_MY_STORE_ACTION = 'UPDATE_MY_STORE_ACTION';



