export const UPLOAD_PICTURE_ACTION = 'UPLOAD_PICTURE_ACTION';
export const DELETE_PICTURE_ACTION = 'DELETE_PICTURE_ACTION';

export const UPLOAD_PICTURE_PRODUCT_ACTION = 'UPLOAD_PICTURE_PRODUCT_ACTION';
export const UPLOAD_PICTURE_CAROUSEL_ACTION = 'UPLOAD_PICTURE_CAROUSEL_ACTION';
export const UPLOAD_PICTURE_SUB_CATEGORY_ACTION ='UPLOAD_PICTURE_SUB_CATEGORY_ACTION';
export const UPLOAD_LIST_PICTURE_RETURN_GOOD_ACTION= 'UPLOAD_LIST_PICTURE_RETURN_GOOD_ACTION';