export const FIND_ALL_PROVINCE_ACTION = 'FIND_ALL_PROVINCE_ACTION';
export const FIND_ALL_DISTRICT_BY_PROVINCE_ACTION = 'FIND_ALL_DISTRICT_BY_PROVINCE_ACTION';
export const FIND_ALL_AWARD_BY_DISTRICT_ACTION ='FIND_ALL_AWARD_BY_DISTRICT_ACTION';
export const FIND_ALL_SERVICE_AVAILABLE_ACTION ='FIND_ALL_SERVICE_AVAILABLE_ACTION';
export const FIND_FEES_ACTION ='FIND_FEES_ACTION';
export const FIND_FEES_GOSHIP_ACTION='FIND_FEES_GOSHIP_ACTION';
export const ADD_ORDER_ACTION = 'ADD_ORDER_ACTION';
export const UPDATE_VOUCHER_ACTION ='UPDATE_VOUCHER_ACTION';