export const FIND_ALL_BY_MASP_ACTION ='FIND_ALL_BY_MASP_ACTION';
export const FIND_ALL_BY_PRODUCT_BY_CATEGORY_ACTION ='FIND_ALL_BY_PRODUCT_BY_CATEGORY';
export const GET_ALL_PRODUCT_BY_KEYWORD_ACTION = 'GET_ALL_PRODUCT_BY_KEYWORD_ACTION';
export const GET_ALL_PRODUCT_BY_SEARCH_ACTION = 'GET_ALL_PRODUCT_BY_SEARCH_ACTION';
export const UPDATE_VIEW_PRODUCT_ACTION ='UPDATE_VIEW_PRODUCT_ACTION';
export const ADD_PRODUCT_VIOLATION_ACTION = 'ADD_PRODUCT_VIOLATION_ACTION';
export const UPDATE_PRODUCT_VIOLATION_ACTION = 'UPDATE_PRODUCT_VIOLATION_ACTION';
export const FIND_ALL_PRODUCT_BY_BRAND_ACTION = 'FIND_ALL_PRODUCT_BY_BRAND_ACTION';
export const FIND_ALL_PRODUCTS_BY_CATEGORY_ACTION ='FIND_ALL_PRODUCTS_BY_CATEGORY_ACTION';
export const FIND_ALL_PRODUCTS_BY_REVIEWS_ACTION ='FIND_ALL_PRODUCTS_BY_REVIEWS_ACTION';
export const FIND_ALL_PRODUCTS_BY_PRICES_ACTION ='FIND_ALL_PRODUCTS_BY_PRICES_ACTION';

