export const SELLER_URL ='SELLER_URL';
export const GET_ALL_PRODUCT_SELLER = 'GET_ALL_PRODUCT_SELLER';
export const GET_ALL_PRODUCT_SELLER_BY_PROVIDERID = 'GET_ALL_PRODUCT_SELLER_BY_PROVIDERID';
export const FIND_ALL_STATISTICAL_SELLER = 'FIND_ALL_STATISTICAL_SELLER';
export const FIND_ALL_PRODUCT_BEST_VIEWS_SELLER ='FIND_ALL_PRODUCT_BEST_VIEWS_SELLER';
export const GET_REFERENCES_PRODUCT ='GET_REFERENCES_PRODUCT';
export const GET_MY_STORE = 'GET_MY_STORE';
