export const OPEN_MODAL = 'OPEN_MODAL';
export const CLOSE_MODAL = 'CLOSE_MODAL';
export const OPEN_SUB_MODAL = 'OPEN_SUB_MODAL';
export const CLOSE_SUB_MODAL = 'CLOSE_SUB_MODAL';
export const OPEN_FORM_MODAL ='OPEN_FORM_MODAL';
export const SET_SUBMIT_FORM_MODAL = 'SET_SUBMIT_FORM_MODAL';
export const OPEN_FIRST_POPUP_MODAL ='OPEN_FIRST_POPUP_MODAL';
export const CLOSE_FIRST_POPUP_MODAL ='CLOSE_FIRST_POPUP_MODAL';