export const FIND_ALL_ORDER_FALSE_ACTION = 'FIND_ALL_ORDER_FALSE_ACTION';
export const FIND_ALL_BY_PROVIDERID_ORDER_FALSE_ACTION = 'FIND_ALL_BY_PROVIDERID_ORDER_FALSE_ACTION';
export const UPDATE_ORDER_ACTION ='UPDATE_ORDER_ACTION';
export const RECEIVED_ORDER_ACTION = 'RECEIVED_ORDER_ACTION';
export const FIND_ALL_ORDERED_BY_MONTH_ACTION ='FIND_ALL_ORDERED_BY_MONTH_ACTION';
export const UPDATE_ORDER_RECEIVED_DATE_TIME_ACTION ='UPDATE_ORDER_RECEIVED_DATE_TIME_ACTION';

export const ADD_RETURN_GOOD_ACTION ='ADD_RETURN_GOOD_ACTION';
export const UPDATE_RETURN_GOOD_ACTION = 'UPDATE_RETURN_GOOD_ACTION';
export const DELETE_RETURN_GOOD_ACTION = 'DELETE_RETURN_GOOD_ACTION';
export const ACCEPT_LIST_ORDER_ACTION = 'ACCEPT_LIST_ORDER_ACTION';

export const ACCEPT_ORDER_DETAIL_SELLER_ACTION = 'ACCEPT_ORDER_DETAIL_SELLER_ACTION';
export const DELETE_ORDER_DETAIL_SELLER_ACTION = 'DELETE_ORDER_DETAIL_SELLER_ACTION';
export const DELETE_ORDER_DETAIL_ADMIN_ACTION ='DELETE_ORDER_DETAIL_ADMIN_ACTION';

export const FIND_ALL_ORDER_MY_STORE_ACTION ='FIND_ALL_ORDER_MY_STORE_ACTION';
export const UPDATE_ORDER_MY_STORE_ACTION ='UPDATE_ORDER_MY_STORE_ACTION';