export const FIND_ALL_COMMENT_ACTION ='FIND_ALL_COMMENT_ACTION';
export const FIND_ALL_REPLY_ACTION ='FIND_ALL_REPLY_ACTION';
export const ADD_COMMENT_ACTION ='ADD_COMMENT_ACTION';
export const UPDATE_COMMENT_ACTION ='UPDATE_COMMENT_ACTION';
export const ADD_REPLY_ACTION = 'ADD_REPLY_ACTION';
export const FIND_REPLY_BY_COMMENT_ACTION = 'FIND_REPLY_BY_COMMENT_ACTION';
export const DELETE_COMMENT_ACTION ='DELETE_COMMENT_ACTION';